
spring:
  resources:
    static-locations: classpath:/static/,file:///home/winnersc/public_html/
  mvc :
    view :
      prefix : /views/
      suffix : .html
  main:
    allow-bean-definition-overriding: true
  datasource:
    url : jdbc:mysql://winners.cultivatingart.in:3306/winnersc_CA_WinnersProfiles?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: winnersc_cultapp
    password: jiCz-e+3%wv7
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
file:
  logos: /home/winnersc/public_html/logos
  eventImages: /home/winnersc/public_html/images
  passport: /home/winnersc/public_html/passport

---
spring :
  profiles : local
  resources:
    static-locations: classpath:/static/,file:///Users/ababu/Documents/Arvind/
  datasource:
    url : jdbc:mysql://localhost:3306/cultivateart?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: MySqlServer

file:
  logos: /Users/ababu/Documents/Arvind/logos
  eventImages: /Users/ababu/Documents/Arvind/images
  passport: /Users/ababu/Documents/Arvind/passport
#spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///C:/images/