
spring:
  resources:
    static-locations: classpath:/static/,file:///home/winnersc/public_html/
  mvc :
    view :
      prefix : /views/
      suffix : .html
  main:
    allow-bean-definition-overriding: true
  datasource:
    #url : jdbc:mysql://mysql-instance1.cezgxrp0uvsq.us-east-2.rds.amazonaws.com/mySqlTest?verifyServerCertificate=false&useSSL=false
    url : jdbc:mysql://103.235.106.62:3306/wwwculti_CA_WinnersProfiles?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url : jdbc:mysql://localhost:3306/cultivateart?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: cultivateart
    username: wwculti_aarvind
    password: i3lT{xS[VNj3
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
file:
  logos: /home/winnersc/public_html/logos
  eventImages: /home/winnersc/public_html/images
  passport: /home/winnersc/public_html/passport

---
spring :
  profiles : local
  resources:
    static-locations: classpath:/static/,file:///Users/ababu/Documents/Arvind/
  datasource:
    url : jdbc:mysql://localhost:3306/cultivateart?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: MySqlServer

file:
  logos: /Users/ababu/Documents/Arvind/logos
  eventImages: /Users/ababu/Documents/Arvind/images
  passport: /Users/ababu/Documents/Arvind/passport
#spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///C:/images/